site_name: "Ohio SPBM Demo"
site_url: http://spbm.ohio.gainwelltechnologies.com/
repo_url: https://dev.azure.com/Gainwell-RPA/RPA/_git/Documentation
repo_name: Gainwell-RPA/RPA/Documentation
theme: 
  name: material
  logo: img/favicon.ico
  icon:
    repo: material/microsoft-azure-devops
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: gainwell
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    #- navigation.sections
    - navigation.tabs
    - navigation.prune
    - search.highlighting
#extra_css:
  #- stylesheets/extra.css